### PR TITLE
Upgrades to CRS v4.0

### PR DESCRIPTION
**Pull request by M4tteoP**
As proposed in the issue, the new tag will follow CRS versioning with a coraza suffix for eventually further changes. Therefore it is going to be `v4.0.0-coraza.1`.

Closes https://github.com/corazawaf/coraza-coreruleset/issues/10

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thoughts on versioning @anuraaga?

**Comment by M4tteoP** [comment]
We might even just stick with `v4.0.0` and only if we actually ever need further changes add the coraza suffix. Adding changes here feels weird to me, I would try to stick to just mirroring the CRS as much as possible

**Comment by anuraaga** [comment]
If I'm not mistaken, if using v4 this will need to go into a folder called v4, or a branch called v4.

Just wondering what is the experience like upgrading from CRS v3 to v4 for example for modsecurity users? In Go, when a library changes major, the import statements have to change and I find it pretty annoying, in the case of this library, there would never be an API change to warrant it. But if the behavior change is too much, then it's probably worth it.

I'm not sure how go would handle the coraza suffix, I have an impression that go interprets suffixes as prereleases or similar. I would just reserve the patch version as space to deviate from upstream, if upstream patch goes up then it goes up here, if something here causes a bump, the patch goes up and doesn't match upstream until the next minor. In practice it shouldn't be a huge issue to not match perfectly.

**Comment by jcchavezs** [comment]
Thanks for the input @anuraaga. I like the idea of having an own patch version, we just need to make sure CRS follows semver (opened an issue in https://github.com/coreruleset/coreruleset/issues/3582). Still I think for 4.0.0 we can happily release `v4.0.0` and very likely we need to change the module name to v4?

**Comment by jcchavezs** [comment]
I am merging this unless further concerns cc @anuraaga

**Comment by jcchavezs** [comment]
Friendly ping @anuraaga

**Review by anuraaga — APPROVED** [review]
Make sure the module name works properly before tagging since it can be easy to require redactions when using non-v1

**Comment by jcchavezs** [comment]
Yeah, I am pretty sure it won't work, it happened to me in the past. We
need to change the module name.

**Comment by M4tteoP** [comment]
I updated the module to `github.com/corazawaf/coraza-coreruleset/v4`, I would merge this and then try to make the [example](https://github.com/corazawaf/coraza-coreruleset/tree/main/example) point to it.

**Review by jcchavezs — APPROVED** [review]

**Pull request merged**
