### PR TITLE
updates to CRS v4.7.0, adds a bit of verbosity to downloadDeps

### PR DESCRIPTION
**Pull request by M4tteoP**

### CODE REVIEW

**Comment by fzipi** [comment]
Can we use renovatebot for this?

**Comment by M4tteoP** [comment]
If it can update https://github.com/corazawaf/coraza-coreruleset/blob/main/version.go and then call `go run mage.go downloadDeps`, probably yes

**Review by jptosso — APPROVED** [review]
LGTM but it makes sense to automate this in the near future

**Comment by M4tteoP** [comment]
Merging, for automation I opened https://github.com/corazawaf/coraza-coreruleset/issues/29

**Pull request merged**
